### `r sym`

```{r, include = TRUE, results = 'asis', warning = FALSE}
setglobals()

mat.ext <- apply(mat, 2, function(m) {
  c(total = prod(1 + m) - 1,
    min   = min(m),
    mean  = mean(m),
    med   = median(m),
    max   = max(m),
    sd    = sd(m))})

rownames(mat.ext) <- c("Total", "Min", "Mean", "Median", "Max", "SD")

tab  <- xtable(round(rbind(mat, mat.ext), 4),
               caption = paste("Compound daily return originated in the HHMM trading strategy for different levels of lags. Lag measured in ticks between the end of the zig-zag and the execution of the trade (zero lag suffers from look-ahead bias).", sym),
               label = paste0("tab:appendix-wf-", sym),
               align = c('r', rep('R', 7)))

print(tab, digits = 4, hline.after = c(-1, 0, nrow(mat), nrow(mat) + nrow(mat.ext)),
      table.placement = "H", width = "\\textwidth", size = "\\tiny")

ptrade <- trades[[as.numeric(which.max(mat[, 3]))]]
cap <- sprintf("Out of sample equity line for %s [%s]", attr(ptrade$tdata, 'symbol'), ptrade$oos)
```

```{r include = TRUE, out.width = '\\textwidth', fig.cap = cap, warning = FALSE}
source('../R/state-plots.R')
setglobals()

plot_topstate_trading(ptrade$tdata[ptrade$oos], 
                      ptrade$zig[ptrade$oos], 
                      ptrade$trades[2:7])
```

\newpage
