---
title: "R Notebook"
output:
  html_document: default
  html_notebook: default
---

[Feature extraction procedure here] Remember, no trend considered without volume!

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE, fig.width = 10, fig.height = 7)
```

# Some set up code

```{r}
library(highfrequency)

# Constants
direction.up =  1
direction.lt =  0
direction.dn = -1

extrema.min  = -1
extrema.max  =  1

volume.up =  1
volume.lt =  0
volume.dn = -1

trend.up =  1
trend.lt =  0
trend.dn = -1

# tdata has to be a xts with two columns price and size
extract_zigzag <- function(tdata, alpha = 0.25) {
  # 1. Initial checks
  tdata <- highfrequency:::.check_data(tdata)
  highfrequency:::tdatacheck(tdata)
  if (is.null(tdata$PRICE) | is.null(tdata$SIZE))
    stop("tdata must include PRICE and SIZE.")

  # 2. Data extraction
  price <- tdata$PRICE
  size  <- tdata$SIZE

  # 3. Zig-zag creation
  lprice     <- lag(price)
  direction  <- ifelse(price > lprice, direction.up,
                       ifelse(price < lprice, direction.dn,
                              direction.lt))
  direction[1,] <- direction.lt

  ldirection    <- lag(direction)
  direction.chg <- direction != direction.lt & ldirection != direction.lt & direction != ldirection

  zigzag <- price[which(direction.chg) - 1, ]
  colnames(zigzag) <- 'price'

  zigzag$start  <- (1:nrow(price))[direction.chg]

  zigzag$end <- lag(zigzag$start, -1) - 1
  zigzag$end[nrow(zigzag)] <- nrow(price)

  zigzag$extrema    <- ifelse(lag(zigzag$price) < zigzag$price, extrema.max, extrema.min)
  zigzag$extrema[1] <- if (zigzag$extrema[2] == extrema.max) extrema.min else extrema.max

  pos.mat  <- as.matrix(zigzag[, c("start", "end")])
  size.mat <- as.vector(size)
  size.ind <- index(size)
  zigzag$size.av <- sapply(1:nrow(zigzag), function(i) {
    pos_start <- pos.mat[i, 1]
    pos_end   <- pos.mat[i, 2]

    sum(size.mat[pos_start:pos_end]) /
      (as.numeric(difftime(size.ind[pos_end], size.ind[pos_start]), units = "secs") + 1)
  })

  # 4. Feature I: local extrema type
  zigzag$f0 <- ifelse(zigzag$extrema == extrema.max, 1, -1)

  # 5. Feature II: trend direction
  price.mat <- as.matrix(zigzag[, "price"])
  zigzag$f1 <- sapply(1:nrow(zigzag), function(n) {
    if (n <= 4)
      return(0)

    e_n <- price.mat[(n - 4):n]

    if (e_n[1] < e_n[3] & e_n[3] < e_n[5]
        & e_n[2] < e_n[4])
      return(1)

    if (e_n[1] > e_n[3] & e_n[3] > e_n[5]
        & e_n[2] > e_n[4])
      return(-1)

    return(0)
  })

  # 6. Feature III: volume strength
  zigzag$size.ratio1    <- zigzag$size.av / lag(zigzag$size.av, 1)
  zigzag$size.ratio2    <- zigzag$size.av / lag(zigzag$size.av, 2)
  zigzag$size.ratio3    <- lag(zigzag$size.av, 1) / lag(zigzag$size.av, 2)

  discretize_sizeratio <- function(ratio, alpha) {
    ifelse(ratio - 1 > alpha, 1, ifelse(1 - ratio > alpha, -1, 0))
  }

  zigzag$size_strength1 <- discretize_sizeratio(zigzag$size.ratio1, alpha)
  zigzag$size_strength2 <- discretize_sizeratio(zigzag$size.ratio2, alpha)
  zigzag$size_strength3 <- discretize_sizeratio(zigzag$size.ratio3, alpha)

  zigzag$f2 <- ifelse(zigzag$size_strength1 == 1 & zigzag$size_strength2 > -1 & zigzag$size_strength3 < 1, volume.up,
                      ifelse(zigzag$size_strength1 == -1 & zigzag$size_strength2 < 1 & zigzag$size_strength3 > -1, volume.dn,
                             volume.lt))
  zigzag$f2[1] <- volume.lt

  # 7. Trend
  zigzag$trend <- ifelse((zigzag$f2 == 1 & zigzag$f0 == 1) | (zigzag$f2 == -1 & zigzag$f0 == -1) | (zigzag$f1 == 1 & zigzag$f1 == -1), trend.up,
                         ifelse((zigzag$f2 == 1 & zigzag$f0 == -1) | (zigzag$f2 == -1 & zigzag$f0 == 1) | (zigzag$f1 == 1 & zigzag$f1 == -1), trend.dn,
                                trend.lt))

  # 8. Legs
  legs <- matrix(c( 1,  1,  1,  1, # Up legs
                    1, -1,  1,  2,
                    1,  1,  0,  3,
                    1,  0,  1,  4,
                    1,  0,  0,  5,
                    1,  0, -1,  6,
                    1, -1,  0,  7,
                    1,  1, -1,  8,
                    1, -1, -1,  9,
                   -1,  1, -1, 10, # Down legs
                   -1, -1, -1, 11,
                   -1,  1,  0, 12,
                   -1,  0, -1, 13,
                   -1,  0,  0, 14,
                   -1,  0,  1, 15,
                   -1, -1,  0, 16,
                   -1,  1,  1, 17,
                   -1, -1,  1, 18),
                 nrow = 18, ncol = 4, byrow = TRUE)

  find_leg <- function(vec, legs) {
    i = 1
    while (i <= nrow(legs)) {
      if (all(vec == legs[i, 1:3]))
        return(legs[i, 4])
      i <- i + 1
    }
    stop("Not a valid leg, watch out!")
  }

  zigzag$feature <- rollapply(zigzag, 1, function(z) {
    find_leg(z[, c("f0", "f1", "f2")], legs)
  }, by.column = FALSE)

  zigzag
}

plot_features <- function(tdata, zigzag, which.features = c('actual', 'extrema', 'trend', 'all')) {
  # 1. Initial checks
  tdata <- highfrequency:::.check_data(tdata)
  highfrequency:::tdatacheck(tdata)
  if (is.null(tdata$PRICE) | is.null(tdata$SIZE))
    stop("tdata must include PRICE and SIZE.")

  # 2. Preparing for legend
  # Sorry for the ugly global!
  legend.list <- list(x = "bottomright", horiz = TRUE, bty = 'n', cex = 0.6)

  list_add <- function(current, ...) {
    dots <- list(...)
    for (i in 1:length(dots)) {
      args.name <- names(dots)[i]
      args.val  <- dots[[i]]
      current[[args.name]] <- c(current[[args.name]], args.val)
    }
    current
  }

  # 2. Data extraction
  price <- tdata$PRICE
  size  <- tdata$SIZE

  # 3. Plots
  opar <- par(no.readonly = TRUE)
  layout(matrix(1:2, nrow = 2, ncol = 1), heights = c(0.75, 0.25))

  # 3. Plot I: Prices, extrema and features
  x.id <- index(tdata)
  y.pr <- as.vector(price)
  x.at <- axTicksByTime(tdata, format.labels = "%H:%M:%S")

  # Price
  par(mar = c(0.0, 5.0, 4.1, 2.1))
  plot(x = x.id, y = y.pr, type = 'l',
       ylab = expression("Price" ~ p[t]), cex.axis = 0.80,
       cex.lab = 0.85, xaxt = 'n', yaxt = 's',
       lwd = 2.0, col = "lightgray")

  axis(3, at = xy.coords(x.id, y.pr)$x[x.at],
       labels = names(x.at), cex.axis = 0.75, las = 2)

  legend.list <- list_add(legend.list,
                          legend = 'Price',
                          pch = NA,
                          lwd = 2,
                          col = 'lightgray',
                          pt.bg = NA)

  if ('actual' %in% which.features) {
    points(x = x.id, y = y.pr,
           pch = 21, cex = 0.8,
           col = NULL, bg = 'black')

    legend.list <- list_add(legend.list,
                            legend = 'Price',
                            pch = 21,
                            lwd = NA,
                            col = 'black',
                            pt.bg = 'black')
  }

  # Features
  z.id <- index(zigzag)

  # Extrema
  if ('extrema' %in% which.features) {
    points(x = z.id, y = zigzag$price,
           pch = 21, cex = 0.8,
           col = NULL, bg = ifelse(zigzag$extrema == extrema.min, 'red', 'green3'))

    legend.list <- list_add(legend.list,
                            legend = c('Local min', 'Local max'),
                            pch = c(21, 21),
                            lwd = c(NA, NA),
                            col = c('red', 'green3'),
                            pt.bg = c('red', 'green3'))
  }

  if ('trend' %in% which.features) {
    trend     <- zigzag$trend
    ltrend    <- lag(zigzag$trend)
    trend.chg <- trend != ltrend
    trend.chg[1] <- TRUE
    trend.id  <- z.id[trend.chg]
    trend.zz  <- zigzag[trend.chg]

    segments(head(trend.id, -1), head(trend.zz$price, -1),
             tail(trend.id, -1), tail(trend.zz$price, -1),
             col = ifelse(trend.zz$trend == trend.up, 'green3',
                          ifelse(trend.zz$trend == trend.dn, 'red',
                                 'blue')),
             lwd = 1)

    legend.list <- list_add(legend.list,
                            legend = c('Bullish', 'Lateral', 'Bearish'),
                            pch = c(NA, NA, NA),
                            lwd = c( 1,  1,  1),
                            col = c('green3', 'blue', 'red'),
                            pt.bg = c(NA, NA, NA))
  }

  if ('all' %in% which.features) {
    all.palette <- colorRampPalette(c('lightgreen', 'darkred'))(18)

    segments(head(z.id, -1), head(zigzag$price, -1),
             tail(z.id, -1), tail(zigzag$price, -1),
             col = all.palette[zigzag$feature],
             lwd = 1)

    legend.list <- list_add(legend.list,
                            legend = c(paste("Bull", 1:9), paste("Bear", 1:9)),
                            pch = rep(NA, 18),
                            lwd = rep( 1, 18),
                            col = all.palette,
                            pt.bg = rep(NA, 18),
                            cex = rep(NA, 0.75))
    legend.list$horiz <- FALSE
  }

  # Legend
  do.call(legend, legend.list)

  # Plot 2 Volume
  y.vo <- as.vector(size)
  vo.ext <- na.locf(cbind(size, zigzag$f2))

  par(mar = c(3.1, 5.0, 0.0, 2.1))
  par(mgp = c(3.0, 1.0, 0.0))
  barplot(height = y.vo,
       # xlab = expression("Time" ~ t),
       ylab = expression("Volume" ~ v[t]),
       cex.axis = 0.80,
       cex.lab = 0.85, xaxt = 'n', yaxt = 's',
       border = 'lightgray',
       col = ifelse(vo.ext$f2 == volume.up, 'green3',
                    ifelse(vo.ext$f2 == volume.dn, 'red',
                           'blue')))
  box()

  title(xlab = expression("Time" ~ t), mgp = c(0.5, 0, 0))

  legend(x = "top",
         legend = c('Upward trend', 'Downward trend', 'Lateral trend'),
         lwd = c(4,  4,  4),
         col = c('green3', 'red', 'blue'),
         bty = 'n', cex = 0.9,
         horiz = TRUE)
  par(opar)
}
```

Now grab some sample data:

```{r}
# Won't be needed when we get the real data
data("sample_tdata")
tdata <- sample_tdata[, 3:4]
storage.mode(tdata) <- "numeric"

zig <- extract_zigzag(tdata, 0.25)

ss <- "2008-01-04 09:31:00/2008-01-04 09:41:00"
```

First plot prices and local extrema:
```{r}
plot_features(tdata[ss], zig[ss], which.features = 'extrema')
```

Now plot the trends marked as bear/bull/lateral:

```{r}
plot_features(tdata[ss], zig[ss], which.features = 'trend')
```

Plot all data (unreadable)

```{r}
plot_features(tdata[ss], zig[ss], which.features = 'all')
```

Finally, my favourite plot!

```{r}
# My favourite setting!
plot_features(tdata[ss], zig[ss], which.features = c('actual', 'extrema', 'trend'))
```
