# Markov chains
Some brief intro. Since this is a preamble for HMM, this writing focus on finite-state Markov chain. It comes in many flavours tho.

## Definition
Let $x_{1:T} = \{x_1, \dots, x_T \}$ be a sequence of regularly spaced observations of arbitrary length $T$. The index $t = 1, \dots, T$ reflects discrete time or space steps. The sequence of random variables has the Markovian property if the probability of moving to the next state depends only on the present state and not on the previous states.

## Transition function (joint distribution)
Let $p(x_t | x_{t-m: t-1})$ be the transition function, where $m$ is finite. Assuming the conditional probabilities are well defined, the joint distribution of a Markov chain of order $m$, or a Markov chain with memory $m$, given the parameters $\mat{\theta}$ can be derived with the chain rule of probability

\[
p(x_{1:T}) = p(x_{1:m}) \prod_{t=m+1}^{T}{p(x_t | x_{t-m : t-1})},
\]

where conditioning on the fixed parameters $\mat{\theta}$ was removed to increase readability.

For first-order Markov chains, by the chain rule of probability, the expression simplifies to
\[
p(x_{1:T}) = p(x_1) p(x_2 | x_1) p(x_3 | x_2) \dots p(x_T | x_{T-1}) = p(x_1) \prod_{t=2}^{T}{p(x_t | x_{t-1})}.
\]

When the transition function is independent of the time index, the chain is called homogeneous, stationary, or time-invariant and the parameters are shared by multiple variables.

If the observed variable only takes one of $K$ possible values, so that $x_t \in S = \{1, \dots, K \}$, the model is called a discrete-state or finite-state Markov chain. The possible values of $x_t$ form a countable set $S$ called the state space of the chain.

## Transition matrix for a finite-state Markov chain (conditional distribution)
In the context of a finite-state Markov chain, the one-step transition matrix $\mat{A}$ is a $K \times K$ stochastic matrix with elements $A_{ij} = p(x_t = j | x_{t-1} = i)$ with $i, \ j \in S$ that satisifies $\sum_{j} = A_{ij} = 1$ for all rows $i$ and $0 \le A_{ij} \le 1$ for all entries $i, \ j$. Each element specifies the probability of transition from $i$ to $j$ in one step. Given the constraints, the matrix has $K(K-1)$ independent parameters.

> This section uses m and k for temporary variables. While the text is clear, k and m are meaningful in the rest of the text. Should I change the temp vars names to, say, r and s?

The $n$-step transition matrix $\mat{A}(n)$ is defined as $A_{ij}(n) = p(x_{t+n} = j | x_{t} = i)$ and represents the probability of getting from $i$ to $j$ in exactly $n$ steps. By definition, $\mat{A}(1) = \mat{A}$. By the Chapman-Kolmogorov equations,

\[
A_{ij}(m + n) = \sum_{k=1}^{K}{A_{ik}(m)A_{jk}(n)},
\]

the probability of transitioning from $i$ to $j$ in exactly $m + n$ steps is the probability of getting from $i$ to $k$ in $m$ steps and then from $k$ to $j$ in $n$ steps, summed up over all $k$. Since this is equivalent to matrix multiplication,

\[
\mat{A}(m+n) = \mat{A}(m) \mat{A}(n),
\]

multiple steps can be naturally computed by exponentiation

\[
\mat{A}(n) = \mat{A}(1)\mat{A}(n-1) = \mat{A}(1)\mat{A}(1)\mat{A}(n-2) = \dots = \mat{A}^n.
\]

## State probabilities (marginal distribution)
Let $\pi_t(j) = p(x_t = j)$ be the probability that the random variable is state $j$ at the interval $t$, and $\mat{\pi}$ be a row vector called the state probability vector. Given the initial distribution $\mat{\pi}_0$, state probabilities for the interval can be computed by $\mat{\pi}_1 = \mat{\pi}_0 \mat{A}$.

A chain is said to have reached its stationary, invariant or equilibrium distribution when the following condition becomes true after many iterations

\[
\mat{\pi} = \mat{\pi} \mat{A}.
\]

This distribution does not always exist, but if does, the process cannot leave after entering this stage. There are different ways to prove if a chain is stationary, the most popular set of necessary conditions include irreducibility, recurrency and a limiting distribution that does not depend on the initial values, which in turns requires aperiodicity. The equilibrium is characterized by the the global balance equations. We refer to XX for a detailed study on the existence of a stationarity distribution and its computation.
